language: python

git:
  depth: 1

python:
  - 3.7

env:
  global:
    - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/conf:$TRAVIS_BUILD_DIR/modules
    - SECRET_KEY=123
    - DATABASE_URL=psql://postgres:@0.0.0.0:5432/blabber_test
    - EMAIL_HOST_PASSWORD=
    - EMAIL_HOST_USER=
    - LOCAL_BUILD=on
    - VK_CLIENT_SECRET=123
    - REDIS_URL=redis://

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install flake8

before_script:
  - pip list
  - psql -c 'create database blabber_test;' -U postgres
  - python3 manage.py migrate

script:
  - python3 manage.py test
  - flake8 --exclude */migrations modules/
