# Generated by Django 3.0 on 2020-04-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventhistory',
            options={'verbose_name_plural': 'User`s history events'},
        ),
    ]
