# Generated by Django 2.2.12 on 2020-05-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhero',
            name='capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userhero',
            name='hero_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_heroes', to='game_skeleton.HeroClass'),
        ),
    ]
