# Generated by Django 3.0 on 2020-05-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_flow', '0002_auto_20200417_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhistory',
            name='points',
        ),
        migrations.AddField(
            model_name='userhero',
            name='wallet',
            field=models.DecimalField(
                decimal_places=4, default=0.0, max_digits=10
            ),
        ),
    ]
