# Generated by Django 2.2.12 on 2020-05-30 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_flow', '0002_auto_20200530_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhero',
            old_name='wallet',
            new_name='coins',
        ),
        migrations.RemoveField(
            model_name='userhero',
            name='datetime_finished',
        ),
        migrations.AlterField(
            model_name='userhero',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to=settings.AUTH_USER_MODEL),
        ),
    ]
