# Generated by Django 2.2.12 on 2020-05-24 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='datetime_last_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
