# Generated by Django 3.0 on 2020-04-17 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_skeleton', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroclass',
            options={'verbose_name_plural': 'Hero classes'},
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'verbose_name_plural': 'Penalties'},
        ),
        migrations.AlterField(
            model_name='gradation',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradations', to='game_skeleton.Rule'),
        ),
    ]
