# Generated by Django 3.0 on 2020-05-04 15:54

from django.db import migrations

import game_skeleton.data as data


def initiate_skeleton(apps, schema_editor):
    for model_name in ('HeroClass', 'Gift', 'Skill', 'Rule', 'Gradation'):
        to_be_created = []
        model = apps.get_model('game_skeleton', model_name)
        instances_data = getattr(data, f'{model_name.upper()}_DATA')

        for instance_data in instances_data:
            to_be_created.append(
                model(**instance_data)
            )
        model.objects.bulk_create(to_be_created)


class Migration(migrations.Migration):

    dependencies = [
        ('game_skeleton', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initiate_skeleton)
    ]
