# Generated by Django 2.2.12 on 2020-08-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_skeleton', '0003_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='game_skeleton.Skill'),
        ),
    ]
